/**
 * SetPasswordPage — Post-Google-registration flow.
 * Users choose a username, then set a password.
 */

import { useState, useContext, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { AtSign, Lock, Check, X, Loader2, ArrowRight, UserPlus, Eye, EyeOff } from 'lucide-react';
import { AuthContext } from '../context/AuthContext';
import { authApi } from '../api/authApi';
import AuthShell from '../components/AuthShell';

export default function SetPasswordPage() {
  const { user, setPassword, setUsername, refreshProfile } = useContext(AuthContext);
  const navigate = useNavigate();
  const location = useLocation();

  // Derive needsUsername from navigation state or user profile (if username was auto-generated or missing)
  const isAutoGenerated = Boolean(user?.username && !user?.usernameChangedAt && /^user_|^[\d]+$/.test(user.username));
  const needsUsername = location.state?.needsUsername ?? (!user?.username || isAutoGenerated);

  const [step, setStep] = useState(() => {
    if (needsUsername) return 'username';
    return user?.username ? 'password' : 'username';
  });
  const [username, setUsernameValue] = useState('');
  const [usernameAvailable, setUsernameAvailable] = useState(null);
  const [usernameChecking, setUsernameChecking] = useState(false);
  const [password, setPasswordValue] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (user?.hasPassword && user?.username && !needsUsername) {
      navigate('/profile');
    }
    if (user?.username && !needsUsername) {
      setStep('password');
    }
  }, [user, navigate, needsUsername]);

  useEffect(() => {
    if (username.length < 3) {
      setUsernameAvailable(null);
      return;
    }
    const timer = setTimeout(async () => {
      setUsernameChecking(true);
      try {
        const res = await authApi.checkUsername(username);
        setUsernameAvailable(res.data.data.available);
      } catch {
        setUsernameAvailable(null);
      } finally {
        setUsernameChecking(false);
      }
    }, 400);
    return () => clearTimeout(timer);
  }, [username]);

  const handleUsernameSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await setUsername(username);
      if (user?.hasPassword) {
        navigate('/profile');
      } else {
        setStep('password');
      }
    } catch (err) {
      setError(err.response?.data?.error?.message || err.response?.data?.message || 'Failed to set username.');
    } finally {
      setLoading(false);
    }
  };

  const handlePasswordSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (password !== confirmPassword) {
      return setError('Passwords do not match.');
    }
    if (password.length < 8) {
      return setError('Password must be at least 8 characters.');
    }
    if (!/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/.test(password)) {
      return setError('Password must contain at least one uppercase letter, one lowercase letter, and one number.');
    }

    setLoading(true);
    try {
      await setPassword(password);
      await refreshProfile();
      navigate('/profile');
    } catch (err) {
      setError(err.response?.data?.error?.message || err.response?.data?.message || 'Failed to set password.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthShell
      title="Almost there!"
      subtitle={step === 'username' ? 'Choose your unique username' : 'Set a strong password for your account'}
    >
      {/* Progress indicator */}
      <div className="flex items-center justify-center gap-2 mb-7">
        <motion.div
          className="w-3 h-3 rounded-full"
          animate={{ backgroundColor: step === 'username' ? 'var(--color-accent)' : 'var(--color-success)' }}
        />
        <div className={`w-14 h-0.5 rounded ${step === 'password' ? 'bg-[var(--color-accent)]' : 'bg-[var(--color-border)]'}`} />
        <motion.div
          className="w-3 h-3 rounded-full"
          animate={{ backgroundColor: step === 'password' ? 'var(--color-accent)' : 'var(--color-border)' }}
        />
      </div>

      {error && (
        <motion.div initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} className="alert alert-danger mb-5">
          {error}
        </motion.div>
      )}

      {step === 'username' ? (
        <form onSubmit={handleUsernameSubmit} className="space-y-5">
          <div>
            <div className="flex justify-between items-center mb-1.5">
              <label htmlFor="username-input" className="block text-sm font-medium">Username</label>
              <span className="text-[11px] text-[var(--color-text-muted)]">3–30 alphanumeric or _</span>
            </div>
            <div className="relative">
              <AtSign size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" />
              <input
                id="username-input"
                type="text"
                placeholder="e.g. alex_coder"
                value={username}
                onChange={(e) => setUsernameValue(e.target.value.replace(/[^a-zA-Z0-9_]/g, ''))}
                minLength={3}
                maxLength={30}
                autoComplete="username"
                required
                autoFocus
                className="pl-10 pr-10"
              />
              <div className="absolute right-3.5 top-1/2 -translate-y-1/2">
                {usernameChecking && <Loader2 size={16} className="animate-spin text-[var(--color-text-muted)]" />}
                {!usernameChecking && usernameAvailable === true && (
                  <Check size={16} className="text-[var(--color-success)]" />
                )}
                {!usernameChecking && usernameAvailable === false && (
                  <X size={16} className="text-[var(--color-danger)]" />
                )}
              </div>
            </div>
            {usernameAvailable === false && (
              <p className="text-xs text-[var(--color-danger)] mt-1.5">
                This username is taken or reserved.
              </p>
            )}
            <p className="text-xs text-[var(--color-text-muted)] mt-1.5">
              You can only change your username once every 30 days.
            </p>
          </div>

          <button
            type="submit"
            className="btn btn-primary w-full"
            disabled={loading || !username || username.length < 3 || usernameAvailable === false}
          >
            {loading ? <Loader2 size={16} className="animate-spin" /> : <ArrowRight size={16} />}
            {loading ? 'Saving...' : 'Continue'}
          </button>
        </form>
      ) : (
        <form onSubmit={handlePasswordSubmit} className="space-y-4">
          <div>
            <label htmlFor="new-password-input" className="block text-sm font-medium mb-1.5">New Password</label>
            <div className="relative">
              <Lock size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" />
              <input
                id="new-password-input"
                type={showPassword ? 'text' : 'password'}
                placeholder="Min 8 chars (uppercase, lowercase, number)"
                value={password}
                onChange={(e) => setPasswordValue(e.target.value)}
                autoComplete="new-password"
                required
                minLength={8}
                autoFocus
                className="pl-10 pr-10"
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)]"
                aria-label={showPassword ? 'Hide password' : 'Show password'}
              >
                {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
          </div>

          <div>
            <label htmlFor="confirm-password-input" className="block text-sm font-medium mb-1.5">Confirm Password</label>
            <div className="relative">
              <Lock size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" />
              <input
                id="confirm-password-input"
                type={showConfirmPassword ? 'text' : 'password'}
                placeholder="Re-enter your password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                autoComplete="new-password"
                required
                className="pl-10 pr-10"
              />
              <button
                type="button"
                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)]"
                aria-label={showConfirmPassword ? 'Hide password' : 'Show password'}
              >
                {showConfirmPassword ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
          </div>

          <button type="submit" className="btn btn-primary w-full mt-2" disabled={loading}>
            {loading ? <Loader2 size={16} className="animate-spin" /> : <UserPlus size={16} />}
            {loading ? 'Setting...' : 'Set Password & Complete'}
          </button>

          {user?.hasPassword && (
            <button type="button" className="btn btn-secondary w-full text-sm" onClick={() => navigate('/profile')}>
              Cancel
            </button>
          )}
        </form>
      )}
    </AuthShell>
  );
}
